name: Echo Demo

on: 
    workflow_dispatch

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello World
              uses: ./.github/actions/action0408.yml
              with:
                version: "0409"
