name: Echo Demo

on: 
    workflow_dispatch

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: Echo Hello World
              uses: ./.github/actions/action0408
              with:
                version: "0409"
